# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.GithubRepoStarsCountPlugin}}
plugins:
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - ZhgChgLi/ZMarkupParser
      - ZhgChgLi/ZReviewTender
      - ZhgChgLi/ZMediumToMarkdown
      - ZhgChgLi/linkyee

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Relli's Stuff"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "Relli"

# Tagline section text
tagline: >-
    Unity nerd, VR enthusiast, Maker, Gamer, and rainbow bird on the internet

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-solid fa-store"
      text: "LilypadVR"
      url: "https://lilypadvr.square.site"
      alt: "LilypadVR storefront"
      title: "LilypadVR storefront"
      target: "_blank"
  - link:
      icon: "fa-solid fa-store"
      text: "Jinxxy"
      url: "https://jinxxy.com/RelliRito"
      alt: "Relli's Jinxxy storefront"
      title: "Relli's Jinxxy storefront"
      target: "_blank"


# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-discord"
      url: "https://discordapp.com/users/371984160132169731"
      title: "Relli's Discord"
      alt: "Relli's Discord"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:rellirito@gmail.com"
      title: "Email: rellirito@gmail.com"
      alt: "rellirito@gmail.com"
      target: "_blank"
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/RadiatedPi"
      title: "Relli's GitHub"
      alt: "Relli's GitHub"
      target: "_blank"

# Footer text
footer: >
    Gwah

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2026  <a href="https://link.zhgchg.li" target="_blank">ZhgChgLi</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
